apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vieventlog-pvc
  labels:
    app: vieventlog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  # storageClassName: default  # Uncomment to use specific storage class
